runtime: python
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
#entrypoint: gunicorn -b :$PORT main:app
#pip3 freeze > requirements.txt <= autoCreate requirements command

runtime_config:
  python_version: 3.7
