runtime: python
env: flex
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
#entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
#entrypoint: gunicorn -b :$PORT main:app
#pip3 freeze > requirements.txt <= autoCreate requirements command
manual_scaling:
  instances: 1

runtime_config:
  python_version: 3.7

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/<PROJECT-ID>:<INSTANCE-REGION>:<INSTANCE-NAME>
  DB_USER: <YOUR_DB_USER_NAME>
  DB_PASS: <YOUR_DB_PASSWORD>
  DB_NAME: <YOUR_DB_NAME>
